### ISSUE TITLE
Stop releasing breaking changes as minors/patches

### ISSUE THREAD

**Issue by jshado1** [electrode-io/electrode#547]
Please (re-)read the specification for npm versioning: [NPM Semver](https://docs.npmjs.com/misc/semver#versions) and [the Semver Spec](http://semver.org/#summary)

Here is an exerp:
>Given a version number MAJOR.MINOR.PATCH, increment the:
>1. MAJOR version when you make incompatible API changes,
>1. MINOR version when you add functionality in a backwards-compatible manner, and
>1. PATCH version when you make backwards-compatible bug fixes.

Upgrading from WebPack 2 to WebPack 3 is a **_MAJOR_** change.

**Comment by jchip** [comment]
what broke?

**Comment by jchip** [comment]
anyways, thanks for filing the issue and sorry for trouble.  Let me know what broke and I will see I can help with fixing it.
 
webpack published 3 and no longer releasing updates to major version 2.  Since the archetypes encapsulates the webpack configs, plugins, and loaders, it's not a breaking change from that PoV.  

However, I will do major when I bump any key dependencies with major in the future.

**Comment by jshado1** [comment]
The upgrade to WebPack 3 causes our build to break with the following error:

```
error: uncaughtException: module.mapChunks is not a function
```

which comes from `electrode-archetype-react-app-dev/node_modules/webpack/lib/ModuleFilenameHelpers.js`

We've hard-fixed our dependency on Electrode to the version immediately before the break caused by #531. We're trying to track down what is triggering that error, but most of the hits from google are about using `exports` instead of `export`, which we don't use.

Thankfully Electrode has changelogs now, which made finding the break much easier.

**Comment by jchip** [comment]
Thanks for that info.

The breaking change from webpack 2 to 3 was the removal of the mangling of `/node_modules/` to `/~/` in stats output etc.  

When updating from webpack 1 to 2 it was a huge change so I major bumped.

We need quite a few things from webpack updates but the mangling change causing a major bump in webpack caused quite a bit of inconvenience.  Upgrading from 2 to 3 was relatively easy though.  I weighted whether to major bump or not but decided not to, in retro not a good idea.

I will look into the breakage you are facing and come up with a fix.

**Comment by jshado1** [comment]
Thanks!

**Comment by jchip** [comment]
base on this `electrode-archetype-react-app-dev/node_modules/webpack/lib/ModuleFilenameHelpers.js` it looks like you have another dependency that might be pulling in webpack 2.  Otherwise webpack should've been installed in `node_modules/webpack`.  Can you please check your node_modules to see all the webpack instances you have and what pulled them?

**Comment by jchip** [comment]
@jshado1 have you had a chance to check your dep?  I'd like to resolve this for you.

**Comment by jshado1** [comment]
@jchip ack! sorry, I missed your previous message. I passed your idea to a colleague for investigation as I'm about to be on holiday for a few days.

Ah, yes. We use WebPack for something else within our project, so it was listed as one of our project dependencies: `"webpack": "^2.6.1"` (which doesn't jive with another dep with a different major). I'll put in a ticket at the top of our backlog to try removing our own dep—just don't suddenly switch Electrode to browserify or something 😜 

Thanks for your help!

**Comment by jshado1** [comment]
Finally getting to this ticket (I was delayed whilst relocating overseas).

An initial problem I found is in [webpack-reporter.js:30](https://github.com/electrode-io/electrode/blob/master/packages/electrode-webpack-reporter/lib/webpack-reporter.js#L30), introduced in #276. This port conflicts with a service we use (I don't know if configure service's port). When it fails, there is no indication what was trying to use that port. It took me 3 hours to track down, manually searching through your source-code.

I see that the `WebpackReporter`'s constructor accepts an `options` argument, which can override the socketPort. Now I'm trying to figure out how—it does not appear to be configurable via config.webpack.js, and the README is a bit empty.

**Comment by jshado1** [comment]
It looks like it could be set in `app-root/config/default.js` based on [electrode-react-webapp Default Options](https://github.com/electrode-io/electrode/tree/master/packages/electrode-react-webapp#default-options), but that doesn't work.

**Comment by jshado1** [comment]
We sorted out the port problems by updating the service with which Electrode conflicted.

After the WebPack issue was sorted, it turns out our main problem was a change to `electrode-react-webapp/lib/express`, on how it handles the promise—it now handles it properly, but we were expecting it to not, and Electrode's fix was not backwards compatible.

It's finally all working now. Now for the real change of upgrading ReactRouter to v4 to avoid that pesky re-mount.
